.TH "" "" "" "" ""
.SH vz\-registro
.RS
.PP
No name given yet
.RE
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ vz\-registro
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ vz\-registro\ status\ \-u\ USER\ \-p\ PASSWORD\ \-r\ REGNUM
\ \ \ \ vz\-registro\ upload\ \-u\ USER\ \-p\ PASSWORD\ \-r\ REGNUM\ \-f\ DATAFILE
\ \ \ \ vz\-registro\ (\ \-h\ |\ \-\-help\ )

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ vz\-registro
\ \ \ \ \-u,\ \-\-user\ USER
\ \ \ \ \-p,\ \-\-password\ PASSWORD
\ \ \ \ \-r,\ \-\-registro\ REGNUM
\ \ \ \ \-f,\ \-\-file\ DATAFILE

Commands:

Arguments:
\f[]
.fi
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
.SH New features
.IP \[bu] 2
add viewport change and change url for report \-\- Apr 4th
16 (../../commit/032660a1a6b0113ca78e082a8726bde49e119b57)
.SH Bug fixes
.IP \[bu] 2
use global casperjs \-\- Apr 4th
16 (../../commit/2f50919103842ddc20b397b45053c27a5627df50)
.IP \[bu] 2
add upload functionality \-\- Apr 4th
16 (../../commit/ef9997ef2d027f2f68e1aa575988f82043ad0368)
